MAGE-#7 Improve GitHub Actions workflow
The github action workflow used to run multiple simulatenous tests,
without any clarity among them.

This change would create a single github action that is aggregrator
action to setup and start the child tests and post the result to gerrit
once done successfully.

Change-Id: Iea51bc64eb59045ab63d3fa8249c5193f25f0a1b

diff --git a/.github/workflows/codeql.yml b/.github/workflows/codeql.yml
--- a/.github/workflows/codeql.yml
+++ b/.github/workflows/codeql.yml
@@ -12,17 +12,13 @@
 name: "CodeQL Advanced"
 
 on:
-  push:
-    branches:
-      - main
-      - 'changes/**'
-  pull_request:
-    branches: [ "main" ]
-  schedule:
-    - cron: '27 22 * * 4'
-
-env:
-  GERRIT_URL: https://gerrithub.io
+  workflow_call:
+    inputs:
+      gerrit_change_id:
+        description: 'Gerrit change id to post the result'
+        required: false
+        type: string
+        default: ''
 
 jobs:
   analyze:
@@ -61,6 +57,11 @@ jobs:
     steps:
     - name: Checkout repository
       uses: actions/checkout@v4
+
+    - name: test
+      run: |
+        echo "Simulating failure"
+        exit 1
 
     # Cache Bazel outputs and external dependencies
     - name: Cache Bazel
@@ -116,36 +117,32 @@ jobs:
       with:
         category: "/language:${{matrix.language}}"
 
-    - name: Extract Change‑Id
-      if: always()
-      id: extract
-      # GITHUB_REF is like "changes/123"
-      run: |
-        change_id="${GITHUB_REF#refs/heads/changes/}"
-        echo "change_id=$change_id" >> $GITHUB_OUTPUT
+  report:
+    name: Report Result to Gerrit
+    runs-on: ubuntu-latest
+    needs: analyze
+    if: ${{ always() && inputs.gerrit_change_id != '' }}
+    steps:
+      - name: Get VOTE
+        if: always()
+        id: vote
+        run: |
+          if [[ "${{ needs.analyze.result }}" == 'success' ]]; then
+            echo "vote=+1" >> $GITHUB_OUTPUT
+          else
+            echo "vote=-1" >> $GITHUB_OUTPUT
+          fi
 
-    - name: Get VOTE
-      if: always()
-      id: vote
-      run: |
-        if [[ "${{ job.status }}" == 'success' ]]; then
-          echo "vote=+1" >> $GITHUB_OUTPUT
-        else
-          echo "vote=-1" >> $GITHUB_OUTPUT
-        fi
-
-    - name: Post Code-Review to Gerrit
-      if: always()
-      shell: bash
-      env:
-        RUN_URL: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
-      run: |
-        echo ${VOTE}
-        curl -u "${{ secrets.GERRIT_USER }}:${{ secrets.GERRIT_PASSWORD }}" \
-             -H "Content-Type: application/json" \
-             -X POST \
-             -d '{
-               "message": "GitHub Actions run on ${{ env.RUN_URL }}",
-               "labels": { "Code-Review": "${{ steps.vote.outputs.vote }}" }
-             }' \
-             "${{ env.GERRIT_URL }}/a/changes/${{ steps.extract.outputs.change_id }}/revisions/current/review"
+      - name: Post Code-Review to Gerrit
+        if: always()
+        shell: bash
+        run: |
+          echo ${VOTE}
+          curl -u "${{ secrets.GERRIT_USER }}:${{ secrets.GERRIT_PASSWORD }}" \
+               -H "Content-Type: application/json" \
+               -X POST \
+               -d '{
+                 "message": "Code Review By CODE-QL result",
+                 "labels": { "Code-Review": "${{ steps.vote.outputs.vote }}" }
+               }' \
+               "https://gerrithub.io/a/changes/${{ inputs.gerrit_change_id }}/revisions/current/review"
